- README.md
- src/builder.rs
- src/host.rs
- src/inbox.rs
- src/io.rs
- src/lib.rs
Facilitates tracing messages in the simulation.
> Bound message type with Debug

- src/builder.rs
- src/host.rs
- src/inbox.rs
- src/io.rs
- src/lib.rs
- tests/ping_pong.rs
Host creation (client, server) is strongly typed.
> Sim supports more than one Message type

- src/sim.rs
This allows clients and test code to spawn tasks, and aligns with
the host execution model.
> `run_until()` spawns on its own rt

- src/lib.rs
- src/role.rs
- src/sim.rs
- src/software.rs
- tests/ping_pong.rs
`Sim::run()` semantics change to run until all registered clients
finish.
> Client hosts get a dedicated rt

- src/role.rs
- src/rt.rs
- src/sim.rs
- tests/connections.rs
- tests/ping_pong.rs
You can’t bounce the bounce if you can’t even pronounce the bounce.
> Bounce, impls #12

- README.md
Copied a commit from Loom https://github.com/tokio-rs/loom/commit/84600d83b947402324b12e7db1d743bfce9de920
> Add a link to Discord room

- .github/workflows/rust.yml
This PR adds Clippy to the CI
#28
> add clippy to CI

- .github/workflows/rust.yml
Add missing stategy in clippy CI.
Maybe it'll work this time?
> add CI missing strategy

- src/builder.rs
- src/config.rs
- src/envelope.rs
- src/host.rs
- src/net/udp.rs
- src/sim.rs
- src/top.rs
- src/world.rs
- tests/async_send_sync.rs
- tests/tcp.rs
> fix clippy warnings

- CHANGELOG.md
- Cargo.toml
- README.md
All dependencies are updated to their latest versions.
> Bump to 0.4.0

- CHANGELOG.md
- Cargo.toml
- README.md
Dependencies updated to latest versions.
> Bump to 0.5.0

- README.md
- src/dns.rs
- src/lib.rs
- src/rt.rs
Moves most of the content to the crate documentation.
> Give docs a refresh

- src/host.rs
- tests/udp.rs
We currently panic when a UDP socket's buffer is full. To better emulate networks, this change drops the packets and logs a tracing message.
I've also added a `bulk_transfer` test to measure the behavior of sending packets faster than the peer can read them.
> fix: drop UDP packets instead of panicking

- src/dns.rs
- change generated host IP addresses to be in 192.168.0.0/24 subnet,
- improve parsing IP addresses (IPv6 support, direct IP binding).
> Minor DNS bugfixes and improvements

- src/sim.rs
This is useful when building more complex simulations, where you need to inspect the system's state after running the simulation.
> Expose whether a host has software running

- src/builder.rs
- src/config.rs
- src/host.rs
- src/world.rs
- tests/tcp.rs
I never thought we'd run through the whole port range, but it seems
some complex setups can hit this.
Add a panic if we run out of ports.
> Add a check for port exhaustion

- src/dns.rs
- src/top.rs
Removes the needless lifetimes.
> Remove needless lifetime

- examples/grpc/README.md
Adds a link to tonic in the grpc example.
> Add link to tonic in grpc example

- .github/workflows/rust.yml
- examples/axum/Cargo.toml
- examples/grpc/Cargo.toml
Enables the required features in the examples.
> Enable required features in example

- Cargo.toml
- src/host.rs
> Update to indexmap 2

- src/rt.rs
- src/sim.rs
> Early exit and tracing for no clients

- src/host.rs
- src/world.rs
I've added the hostname to the error message. While debugging an issue I found this useful. I want to put this back so others can benefit from this too.
> Improve host ports exhausted panic message

- src/sim.rs
This PR ticks the clock on hosts that are not actively running, so if they are ever restarted their clock will be synchronized with the time passed in the simulation. This allows us to use `sim_elapsed()` as a form of global clock, which every host can use. 
Relevant issue: #207
> Keep clocks of crashed hosts in-sync with the simulation.

- .github/workflows/rust.yml
Ref: https://crates.io/crates/cargo-semver-checks
Shamelessly copied from tokio repo: https://github.com/tokio-rs/tokio/blob/e4a39d2ef6a389cceaebfa54f89ec04b5651c1e0/.github/workflows/ci.yml#L473
> add cargo-semver-check to CI
