tokio-rs/turmoil

src/builder.rs, src/dns.rs, src/host.rs, src/io.rs, src/lib.rs, tests/hello_world.rs, tests/ping_pong.rs
All simulation state is now housed within `Inner`.
Add a simple ping/pong test.
=> Move Dns into Sim's shared state

Cargo.toml, src/sim.rs
Trying to remove the `'static` requirement while still having the `run_until` task have its own runtime.
=> remove static requirement

src/sim.rs, tests/ping_pong.rs
The flag for `is_finished` needs to ensure *all* clients are finished
rather than just the last one.
=> Fix termination bug in Sim::run()

Cargo.toml, src/connection.rs, src/lib.rs, tests/connections.rs
Real world servers often use concurrency for processing requests.
Protocols also lean on message ordering per connection, ie TCP. Neither
of these features were available with the current `Io` implementation.
This change overlays connection support on top of `Io` by multiplexing
through an actor. A simple TCP-like state machine is used to initiate and
accept connections.
=> Add distinct connections over Io

README.md, src/connection.rs, src/host.rs, src/io.rs, src/lib.rs, src/sim.rs, src/world.rs, tests/connections.rs, tests/ping_pong.rs
This approach has a few advantages:
- Less restrictive typing: send and recv can have different
message types.
- Simpler registration and io access for hosts.
- Opens the door for free functions that allow connecting and
accepting connections.
=> Move io to free functions

src/envelope.rs, src/host.rs, src/lib.rs, src/top.rs, src/world.rs, tests/ping_pong.rs
This commit introduces `turmoil::hold` and `::release` that temporarily hold packets between a sender and receiver. Unlike the partition and repair methods, held packets are not dropped. Instead, they are delivered after release is called.
=> Implement hold and release, impls #11

src/envelope.rs, src/host.rs
Cleanup the previous change, which relied on special semantics for None.
=> Add an enum for delivery instructions

.github/workflows/rust.yml, Cargo.toml, README.md, src/lib.rs, src/readme.rs
In a recent commit, I changed the API for starting a host to require a future factory. The example in the README broke, but the PR was still merged.
In this commit, we use Github actions to run `cargo test --verbose` PRs to main (and adhoc pushes). For now, this just tests on ubuntu as we have no platform specific code.
In addition, we run the README as a doctest. This slightly harms the README because the example is no longer copy-paste ready. In particular, the `#[test] fn simulation() {  }` chrome is now removed so as to work within the doctest framework. I think that's OK, especially since we ship real examples in test/.
Finally, the actual bug was fixed by adding a tunnel, down which no variables slide.
---
Note that I pushed this to my fork and the CI worked: …
=> Fix error in README.md

src/builder.rs, src/role.rs, src/sim.rs, tests/ping_pong.rs
While the `Future` must be `'static`, the `Fn` to generate it does
not need to be.
Specifying an explicit lifetime here makes it simpler to write tests
that capture state in the closure.
=> Use an explicit lifetime for host's software factory

src/host.rs, src/io.rs, src/sim.rs, src/world.rs
- s/send/embark to better self document what happens
- `send` bumps host version: Originally only recv bumps this, but
connections will bump on connect and accept, so this prepares for
that.
- minor refactoring for send and recv paths
- s/Arc/Rc
=> Some cleanup for existing networking

Cargo.toml, src/host.rs, src/io.rs, src/lib.rs, src/log.rs, src/net/listener.rs, src/net/mod.rs, src/net/stream.rs, src/version.rs, src/world.rs, tests/net.rs
The `net` module mirrors [tokio::net](https://docs.rs/tokio/latest/tokio/net/index.html).
Hosts now have the ability to bind their current `SocketAddr`,
which sets up a listener queue for accepting connections.
Connections are identified using a `SocketPair`, which is
a tuple of `version::Dot`. Note that each network operation
bumps the host's version number ensuring this is unique.
Support for "bounce" and "drop" (via RST) will follow in a subsequent
change set.
=> Add support for simulated TCP connections

README.md, src/envelope.rs, src/host.rs, src/lib.rs, src/net/mod.rs, src/net/stream.rs, src/net/udp.rs, src/world.rs, tests/net.rs, tests/ping_pong.rs
Most notably, this fixes a bug in the accept queue where syn's not
eligible for delivery block other connections from proceeding.
A regression test is added for this specific scenario.
=> Follow up on late comments to #35

Cargo.toml, src/dns.rs, src/envelope.rs, src/host.rs, src/lib.rs, src/net/udp.rs, src/top.rs, src/tracing.rs, src/world.rs, tests/udp.rs
Here is an example trace ->
```txt
2022-10-20T21:20:02.325402Z  INFO turmoil: New server @127.0.0.1
2022-10-20T21:20:02.325633Z  INFO turmoil: New client @127.0.0.2
2022-10-20T21:20:02.325828Z  INFO turmoil: Bind 127.0.0.1:1738 UDP
2022-10-20T21:20:02.325937Z  INFO turmoil: Bind 127.0.0.2:1738 UDP
2022-10-20T21:20:02.325986Z  INFO turmoil: Send 127.0.0.2:1738 127.0.0.1:1738 UDP [0x70, 0x69, 0x6E, 0x67]
2022-10-20T21:20:02.328982Z  INFO turmoil: Delivered 127.0.0.1:1738 127.0.0.2:1738 UDP [0x70, 0x69, 0x6E, 0x67]
2022-10-20T21:20:02.329067Z  INFO turmoil: Recv 127.0.0.1:1738 127.0.0.2:1738 UDP [0x70, 0x69, 0x6E, 0x67]
2022-10-20T21:20:02.329092Z  INFO turmoil: Send 127.0.0.1:1738 127.0.0.2:1738 UDP [0x70, 0x6F, 0x6E, 0x67]
2022-10-20T21:20:02.329122Z  INFO turmoil: Unbind 127.0.0.1:1738 …
```
=> Add simple simulation tracing

Cargo.toml, README.md, src/dns.rs, src/envelope.rs, src/host.rs, src/net/listener.rs, src/net/mod.rs, src/net/stream.rs, src/net/udp.rs, src/sim.rs, src/top.rs, src/tracing.rs, src/world.rs, tests/tcp.rs
`TcpListener` and `TcpStream` are implemented with the minimal APIs mirrored
from `tokio::net` to be functional.
Tracing is updated to use structured k/v pairs.
=> Simulated TCP streams

src/host.rs, src/net/listener.rs, src/net/stream.rs, tests/async_send_sync.rs, tests/tcp.rs
Interior mutability was initially chosen to align with the `tokio::net`
API. This actually diverged, as the listener could not be moved into
spawned tasks.
We go back to a simple `Notify` and `VecDeque` channel, which when Arc'd
can be moved into spawned tasks.
=> TcpListener implements `Send`

src/host.rs, src/net/mod.rs, src/net/tcp/listener.rs, src/net/tcp/mod.rs, src/net/tcp/split_owned.rs, src/net/tcp/stream.rs, tests/async_send_sync.rs, tests/tcp.rs
Refactor the stream to enable splitting into distinct read/write
halfs, with the ability to reunite halfs from the same stream at a
later point in time.
Each half is "owned" and may move to spawned tokio tasks.
=> Split and reunite `TcpStream`s

src/rt.rs, src/sim.rs, src/world.rs
I observed a bug where moving a `TcpListener` into a spawned task
was not dropped after crash returns. If you bounce the host, it would
error with `ErrorKind::AddrInUse`.
Now we also drop and replace the runtime, which has the desired
effect of blocking the calling thread until all tasks have dropped,
cleaning up all resources.
=> Fix host crash behavior

src/rt.rs, src/sim.rs
Each invocation of `run()` moves the simulation's logical time forward. Systems that use logical clocks need this information to build simulated primitives, ie [Lamport clock](https://en.wikipedia.org/wiki/Lamport_timestamp).
By exposing both an epoch for the simulation and the elapsed time, we can now build application level logical clocks.
=> Expose the sim's epoch and elapsed duration

README.md
This PR is adding a line to the readme mentionning the need for the `tokio_unstable` features for a project to compile.
=> add line about running in readme

src/builder.rs, src/config.rs, src/host.rs, src/role.rs, src/rt.rs, src/sim.rs, src/world.rs
Previously, we simply tracked the elapsed duration after each tick. This makes it impossible to get a host-level view of elapsed time from within the software. Software _could_ use an `Instant` + base `SystemTime` approach, but the `Instant` has issues across host restarts as the tokio runtime is replaced.
This change fixes that by tracking bulk elapsed time on each tick and uses that as a base along with a new `Instant` that is set each time the software runs. With the elapsed base we can accurately give a current elapsed time to running software and survive restarts.
I admit this isn't the cleanest, but I can't figure out how to use a single `Instant` across runtimes, and re-using the runtime seems a lot more complicated.
=> Fix host elapsed time across software restarts

src/dns.rs, src/lib.rs, src/net/tcp/listener.rs, src/net/tcp/stream.rs, src/net/udp.rs
Rename `ToSocketAddr` to `ToSocketAddrs` to make turmoil more compatible with tokio.
My motivation is that I am trying to mock parts of tokio with turmoil in my project, behind a feature flags. This is only possible is the crates are at least name-compatible.
=> rename ToSocketAddr to ToSocketAddrs

README.md, src/role.rs, src/sim.rs, tests/tcp.rs, tests/udp.rs
This change only captures a host failure during a run of a simulation. Bounces assign a new JoinHandle which is checked after a subsequent run. This change is a breaking change for those that do not produce a `Result` or loop forever.
Since this approach removes the host runtime from the `rts` map when it completes, a few of the existing tests would fail as all of the resources owned by completed hosts would be dropped. I opted to use `future::pending()` to prevent the host from finishing on the happy path, as this seems preferable. However, I can handle hosts differently if the previous behavior is preferred.
This addresses #36.
=> Add host error support

README.md, src/rt.rs
We use `unhandled_panic` to forward host software panics 
as test failures.
Consider the test:
```rust
#[test]
fn panics() -> turmoil::Result {
let mut sim = turmoil::Builder::new().build();
sim.host("host", || async {
tokio::spawn(async { panic!("boom!") });
future::pending().await
});
sim.client("client", async { Ok(()) });
sim.run()
}
```
With `tokio_unstable` the test fails, which can be useful for
uncovering issues early.
Forcing this is a bit invasive for consumers of the crate, so
instead we make it enabled conditionally.
=> Make tokio unstable opt in

src/sim.rs
Break out the inside of the `run()` loop into a public method
to allow callers to create their own event loop.
Callers can now run custom logic each iteration of the simulation
to support richer test scenarios.
More changes will follow to add finer grained control over the
network.
=> Expose a mechanism to manually drive the Sim

src/envelope.rs, src/lib.rs, src/sim.rs, src/top.rs
The sim now supports iterating each host pair's network link, as well
as each message that is currently "in flight" on the network.
Link and message metadata is exposed. We can also now force delivery
of messages.
In combination with the step capabilities that were recently added we
now have the ability to run more complex test scenarios.
=> Add network topology introspection

.github/workflows/rust.yml, Cargo.toml, src/dns.rs, src/envelope.rs, src/host.rs, src/lib.rs, src/net/tcp/listener.rs, src/net/udp.rs, src/rt.rs, src/sim.rs, src/world.rs, tests/tcp.rs, tests/udp.rs
This allows various host interactions via regex matches to reduce the effort to induce more complex interactions. While this has changed the explicit API contract in some cases, this should not affect most test cases as the `ToIpAddrs` trait implements `ToIpAddr` for all `T` that implement `ToIpAddr`.
=> Add option to query hosts via regex

Cargo.toml, README.md, examples/grpc/Cargo.toml, examples/grpc/README.md, examples/grpc/build.rs, examples/grpc/helloworld.proto, examples/grpc/src/main.rs
This commit adds a simple gRPC example using tonic and hyper.
=> Add `gRPC` example

src/sim.rs, src/top.rs
We've got support for overriding the max, but it is also useful to
set a single latency duration for links.
Add another method on `Sim` to support this use case.
=> Set message latency per link

src/dns.rs, src/host.rs, src/net/tcp/listener.rs, src/net/tcp/stream.rs, src/sim.rs, src/top.rs, src/world.rs, tests/tcp.rs
Implementation proposal for #79 .
It does not use topology under the hood, skips the chain.
The messages are not queued like in the topology, but are delivered to hosts directly.
If the approach is acceptable, I can add an another CR for UDP.
=> Add support for localhost binding in TCP (#79)

src/dns.rs, src/host.rs, src/net/tcp/listener.rs, src/sim.rs, src/top.rs, src/world.rs, tests/tcp.rs
This reverts commit feca39de88fa3313b1f5c33ced3ace221c6a2b82.
After discussion with @mcches, we established that:
a) IPv6 is supported by conicidence, is partially completed, we don't want to ship that.
b) There is a bug which treats localhost communication as non-localhost.
c) We don't want to introduce localhost communication into a router (top.rs) and want to keep it local to the host, as an OS would.
This will be rewritten, connected to #79
=> Revert "Add support for loopback in TCP (#83)"

src/net/udp.rs
I'm working on integrating turmoil with s2n-quic and needed a way to query the address that the socket is bound to. This is available on the [`tokio::net::UdpSocket`](https://docs.rs/tokio/latest/tokio/net/struct.UdpSocket.html#method.local_addr).
=> feat: add local_addr to net::UdpSocket

src/net/tcp/stream.rs, src/net/udp.rs, tests/tcp.rs
Buffer the remainder of a received data segment to serve subsequent
reads.
=> Fix AsyncRead impl for TcpStream

src/host.rs, src/net/tcp/listener.rs, src/net/udp.rs, tests/tcp.rs, tests/udp.rs
=> Support ephemeral port assignments on bind

src/lib.rs, src/sim.rs
Applying a "hold all" panics as the resolution does not take into
account equal `IpAddrs`s.
This fixes #115.
=> Filter out equal `IpAddr`s for regex matching

src/dns.rs, tests/tcp.rs, tests/udp.rs
There is an inconsistency in address resolution / parsing.
The trait `ToIpAddr` interprets strings that can be parsed as an `IpAddr` as 
domain names instead of parsing the address. `ToSocketAddr` however will
parse the Ip part of the address if possible. To remove this inconsistency 
`ToIpAddr` will now always interpret strings that can be parse to a `IpAddr` as `IpAddr`.
Without this change:
```rust
use turmoil::{*, net::*};
fn main() -> Result {
let mut sim = Builder::new().build();
sim.client("192.168.42.42", async move {
let addr = UdpSocket::bind("0.0.0.0:0").await.unwrap().local_addr().unwrap();
// addr will be 192.168.0.1:<port>, interpreting the clients name as a domain addr
Ok(())
});
sim.client("192.168.57.57".parse::<IpAddr>().unwrap(), async move {
let addr = …
```
=> Remove inconsistent address resolution

src/host.rs, tests/tcp.rs, tests/udp.rs
There was a bug where binding an already bound port would wipe the existing bind before returning an ADDR_IN_USE error. This change resolves the bug by erroring before we update the host's binds.
=> Fix bug in binding an in use port

src/host.rs, src/net/tcp/listener.rs, src/net/tcp/stream.rs, src/net/udp.rs, tests/tcp.rs, tests/udp.rs
This changes adds UDP and TCP support for loopback. Packets sent over loopback
do not flow through the topology, instead they are sent directly from the host
back to itself - somewhat modeling how the real world works. The affects of
this implementation are that network manipulation APIs do not work on loopback
traffic. However, this approach gets incrementally closer towards full loopback
support and unblocks most use cases.
The implementation is a bit of hack. I think where we want to get to is full 
support for multiple interfaces. For example, hosts should be allowed to have 
both an v4 and v6 ip addr. This will require a bit of a lift due to how hosts 
are identified by an IP address.
=> Add support for loopback

src/dns.rs, src/sim.rs, tests/dns.rs
Turmoil supports the creation of clients/hosts bound to any address that `impl ToIpAddr`.
This allows for then creation of nodes, bound to static IP addresses. Such nodes
will not appear in the internal mappings of `Dns`, since they have no hostname.
`Dns::reverse` however expects that all nodes (all inputs would be more correct) are contained
in the dns mapping. If this assumption is broken, `Dns::reverse` panics. This means that any use of
`Dns::reverse` in combination with a statically bound address will panic. 
The problem: If a tracing subscriber is active, internal traces will attempt to use `Dns::reverse` once
when the node is initialized, thus crashing the simulation (world.rs:107).
I See three solutions:
If a reverse lookup does not find any entry in the dns mapping, it returns …
=> Fix reverse dns lookups on static binds

src/builder.rs, src/config.rs, src/host.rs, src/sim.rs, src/world.rs, tests/tcp.rs, tests/udp.rs
Behavior stays the same for now, but the values can at least be modified for chatty use cases.
=> Make socket buffer capacity configurable

src/host.rs, src/net/tcp/listener.rs, src/net/tcp/stream.rs, src/net/udp.rs, src/rt.rs, src/sim.rs, src/top.rs, src/world.rs
Some improvements to tracing with turmoil:
- All nodes now have a node-span, to add information about the currently active node to all tracing events
- These spans are stored in `Rt` and `Host` to cover all codepaths that may emit events
- All internal tracing events now share a common structure (`src`,`dst`, ..., `msg`)
- `src` now always represents the source of the packet, the tracing record was about  (`src` of SYN is client, `src` of SYN-ACK is server)
=> Tracing improvments

src/lib.rs, src/sim.rs, src/world.rs
Expose functions to control network behaviour on the simulator.
=> Add hold, release, repair, partition to simulator

src/net/tcp/listener.rs, src/net/tcp/stream.rs, src/net/udp.rs, src/top.rs, src/world.rs, tests/tcp.rs, tests/udp.rs
=> Return errors instead of panicking

src/host.rs, src/net/tcp/stream.rs, src/net/udp.rs, tests/tcp.rs, tests/udp.rs
This should resolve #135.
Current workaround for loopback from #118 does not allow connecting to the same host when using the public ip. This change extends the workaround to allow for that, unblocking additional use cases pending a larger rework to fully support multiple interfaces (see #132)
=> Extend loopback workaround

src/lib.rs, src/sim.rs, src/world.rs
This provides a path for scanning all hosts in the network via existing functionality, which is useful for building host discovery.
=> Add reverse DNS resolution capabilities

Cargo.toml, src/net/tcp/stream.rs
If the stream is shutdown manually it sends a FIN on the write half,
however we don't check the state in the drop implementation, which led
to a duplicate FIN being sent.
To fix, `is_shutdown` is checked before sending the FIN.
=> Fix duplicate FIN in the drop glue

src/net/tcp/stream.rs, tests/tcp.rs
Do not send a Fin upon the write half drop if the stream is already shutdown but still perform the socket pair clean up.
=> Fix ephemeral port leak upon tcp stream shutdown

src/builder.rs, src/top.rs
Previously if you specify a `min_message_latency` greater than the default `max_message_latency`, the test would fail with a tokio error: `overflow when subtracting durations`. This change updates the builder to assert that the min/max latencies are valid on build.
=> Fix subtraction overflow bug with latency

src/builder.rs, src/config.rs
This commit fixes the turmoil sim builder by removing the `rng`
function. Currently the `build` function ignores the `rng` set on the
builder, and due to the boxing of the value there is no easy way to
repeatedly build a sim with the same `rng`. We would need to add the
ability to clone the boxed rng, which requires some complicated trait
bounds and a different breaking of the interface. This is simpler and
fixes the bug where rng was ignored during building.
This is a breaking change:
- `rng` is removed from the builder, as it was not delivering its
expected behaviour. Users now need to explicitly specify
`build_with_rng`.
=> Fix builder to use provided rng

src/builder.rs, src/config.rs, src/net/udp.rs, src/sim.rs
Add documentation to the sim builder and the config, particularly focused on default values.
Also fix a few errors that emerged from running `cargo doc`.
=> Add docs for the builder and config focused on defaults

src/builder.rs, src/net/tcp/stream.rs, src/net/udp.rs, src/sim.rs, src/world.rs, tests/tcp.rs, tests/udp.rs
- Avoid trying to spawn on teardown when the rt is gone
- Deliver loopback packets in the next step to better align with
how remote networking works.
=> More fixes for loopback networking

.github/workflows/rust.yml
- Update actions/checkout action
- Use cargo directly instead of unmaintained actions-rs/cargo action
- Use [dtolnay/rust-toolchain](https://github.com/dtolnay/rust-toolchain) instead of unmaintained actions-rs/toolchain action
See also https://github.com/tokio-rs/tokio/pull/5316 for the context of unmaintained actions and alternatives.
=> Update actions/checkout action and replace unmaintained actions-rs actions

examples/axum/Cargo.toml, examples/axum/src/main.rs
The internals of the various components of this example have changed significantly. While this works, I'd appreciate a careful review to ensure that it is correct in addition to functional.
Thank you!
=> Update Axum example to use axum 0.7 and hyper 1.

examples/grpc/src/main.rs, src/host.rs, src/lib.rs, src/sim.rs, src/world.rs
Previously, we only exposed `turmoil::elapsed` which returned the elapsed virtual time for the currently executing host. If you step your simulation for some duration before registering a host then the host's elapsed time will be less than the overall sim elapsed time.
We didn't want to make a breaking API change for this, so opted to add a new function (`turmoil::sim_elapsed`). This function returns an `Option` so that the caller can gracefully handle failure (`turmoil::elapsed` will crash if called outside of an executing host, for example). This makes it easier to use `sim_elapsed` for things like logging elapsed time via the std tracing subscriber (there's an example of how to do this in the `grpc` example).
One sharp edge I ran into is that we sometimes do tracing in this crate …
=> Add `turmoil::sim_elapsed` for retrieving total simulation virtual time

src/lib.rs, src/sim.rs, src/world.rs
- **Make sim_elapsed function safe to call outside of simulation**
=> Make sim_elapsed function safe to call outside of simulation

Cargo.toml, src/builder.rs, src/config.rs, src/rt.rs, src/sim.rs, tests/tokio_io.rs
**Pull request includes:**
* activation of tokio io driver to  enable _net_, _process_ & _signals_ within runtime (for our use-case we need _net_)
* some additional formating stuff
=> Enable tokio io driver

src/builder.rs, src/config.rs, src/sim.rs
This was quite useful in our tests, where the outcome of a multi-node simulation is sensitive to processing order.
Plumbed through as a boolean option through Config/Builder, w/ the default being `false` (current behavior)
=> Add ability to run hosts in random order

src/net/tcp/stream.rs, tests/async_send_sync.rs, tests/tcp.rs
Add `TcpStream::try_write()` and `WriteHalf::try_write()`. 
These allow for a result-based synchronous write attempt.
=> Add try_write to TcpStream

src/net/udp.rs
Allows structs that hold a socket to derive `Debug` automatically.
=> Implement Debug for UdpSocket

Cargo.toml
> Some crates might use custom cfgs, like loom, fuzzing or tokio_unstable that they expected from the environment (RUSTFLAGS or other means) and which are always statically known at compile time. For those cases, Cargo provides via the [lints] table a way to statically declare those cfgs as expected.
Reference: https://blog.rust-lang.org/2024/05/06/check-cfg.html
Fixes https://github.com/tokio-rs/turmoil/issues/182
=> Add unexpected_cfgs lint exception, fixes #182

src/host.rs, src/lib.rs, src/world.rs, tests/tcp.rs
This commit adds a utility method to count the number of established tcp streams on a given host (or the current host). This can be used to verify connections have been cleaned up, which is sometimes tricky to reason about due to a combination of how tcp cleans up and how Drop works.
=> Add established_tcp_stream_count{,_on}

src/sim.rs, src/top.rs, src/world.rs
This is an attempt to solve #167 .
=> Allow one way partitionings

examples/grpc/Cargo.toml, examples/grpc/build.rs
`compile_fds` can be used to compile the file descriptor set.
=> Use compile_fds to compile file descriptor set

examples/axum/src/main.rs, examples/grpc/src/main.rs
`EnvFilter`'s config can be used to set the default tracing level instead of editing the environment variable.
=> Use EnvFilter config to set default tracing level

Cargo.toml
These crates does not seem to be used.
=> Remove unused crate from dependency

src/rt.rs
Resolves unused mutable warning.
=> Resolve unused mutable warning

Cargo.toml, src/rt.rs, src/sim.rs
The APIs from standard library can be used instead of futures crate's ones.
=> Remove futures crate from dependency

src/net/tcp/split_owned.rs, src/net/tcp/stream.rs, tests/tcp.rs
Our codebase is using the `peek` functions that Turmoil does not model. It seemed easy to add so here's an attempt to add them for TCP.
- [poll_peek](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.poll_peek)
- [peek](https://docs.rs/tokio/latest/tokio/net/struct.TcpStream.html#method.peek)
=> Add peek to TcpStream.

src/net/tcp/listener.rs, tests/tcp.rs
This PR makes `TcpListener::accept` try to accept the next connection without waiting for a notify, if the previous connection couldn't be established because the peer already went away.
The change is meant to fix a bug where a pending connection sometimes wouldn't be accepted. Consider this series of events:
* Server runs `TcpListener::accept`. There are no connections pending, so it starts waiting on the `notify`.
* Client 1 sends a SYN, which gets pushed to `ServerSocket::deque` and `ServerSocket::notify` is notified.
* Client 2 sends a SYN, which gets pushed to `ServerSocket::deque` and `ServerSocket::notify` is notified.
* Client 1 goes away.
* Server wakes up because the `notify` was notified.
* Server tries to accept the connection from client 1, which fails because client 1 went …
=> TcpListener: drain all pending accepts

examples/grpc/Cargo.toml
It is already defined at the dependencies section.
=> Remove prost from build-dependencies
